### ISSUE TITLE
Could you please update repository with last version?

### ISSUE THREAD

**Issue by michal-josef-spacek** [kimryan/Readability#1]
btw: There was a change in SYNOPSIS in 1.24. I don't think that is ok. All SYNOPSIS sections are in verbatim mode.

**Comment by kimryan** [comment]
Was just waiting for this to pass CPAN testers, will update now. Synopsis was changed to document an additional method. I'm not sure what verbatim mode means.

**Comment by michal-josef-spacek** [comment]
Verbatim mode is mode like `<pre>` in HTML.
In POD each line has space on begin.

From man perlpod:
```
Verbatim Paragraph
    Verbatim paragraphs are usually used for presenting a codeblock or other text which does not require any special parsing or formatting, and which shouldn't be wrapped.

    A verbatim paragraph is distinguished by having its first character be a space or a tab.  (And commonly, all its lines begin with spaces and/or tabs.)  It should be reproduced exactly, with tabs assumed to
    be on 8-column boundaries.  There are no special formatting codes, so you can't italicize or anything like that.  A \ means \, and nothing else.
```

You could look at difference in SYNOPSIS section in presentation in metacpan.org:
https://metacpan.org/release/KIMRYAN/Lingua-EN-Fathom-1.24/view/lib/Lingua/EN/Fathom.pm
vs
https://metacpan.org/release/KIMRYAN/Lingua-EN-Fathom-1.23/view/lib/Lingua/EN/Fathom.pm

**Comment by kimryan** [comment]
Have updated now and restored indent of the synopsis block.

**Comment by michal-josef-spacek** [comment]
Thanks.

Plus https://github.com/kimryan/Readability/pull/2

**Comment by kimryan** [comment]
Moved =SYNOPSIS POD marker to start of line, should be all ok now

**Comment by kimryan** [comment]
as above

**Comment by michal-josef-spacek** [comment]
Thanks :-)
